on:
  pull_request:
    types: [opened, synchronize]

jobs:
  evaluator_job:
    runs-on: ubuntu-18.04
    name: Evaluator job
    steps:
      - uses: actions/checkout@v2
      - name: Evaluator step
        id: evaluator
        uses: betrybe/react-scripts-evaluator-action@fix/remove-ci-true-flag
        with:
          repository-test-name: 'betrybe/sd-0x-block14-project-movie-card-library-crud-tests'
          repository-test-branch: 'jeanpsv-patch-1'
      - name: Store evaluation step
        uses: betrybe/store-evaluation-action@v2
        with:
          evaluation-data: ${{ steps.evaluator.outputs.result }}
          environment: production
          pr-number: ${{ github.event.number }}
